### ISSUE TITLE
Why there are no tests?

### ISSUE THREAD

**Issue by abdelrahmanahmed** [valorin/pwned-validator#1]
Thank you for your awesome package but i have a question :

> Q: Where are the tests?
> A: To properly test this code, we need to hit the web service. I don't want to automate that, to avoid abusing this fantastic service. Instead, since it is an incredibly simplistic validator, I've opted to manually test it for now.

I don't get it , why you don't mock the service and write your tests based on it?

**Comment by valorin** [comment]
In it's current state, there isn't a service to be mocked. The Pwned rule calls the `curl_*()` methods directly, which can't be (easily) mocked as-is. But yes, I could extract that into another class and pass a mocked version into the Rule for validation.

Leave it with me and I'll write some tests. 😄
