### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by christian98** [valorin/pwned-validator#16]
Hey, i see that you already added support for Laravel 9 to your `master` branch. But there is no tagged version yet. Would be nice to have this tagged soon, please. We dont want to install a `dev-master` version to our production environment.

**Comment by valorin** [comment]
Oops, sorry about that! I should have tagged it as soon as I bumped the version.

It's been tagged now. 😁

**Comment by christian98** [comment]
No Problem. Thank you very much!
