### ISSUE TITLE
Laravel 6 compatibility

### ISSUE THREAD

**Issue by lsfiege** [valorin/pwned-validator#6]
Hi! I was wondering if this package will have support for Laravel 6

Greetings!

Edit: I have made a pull request to help you, let me know if you need some help :)

**Comment by valorin** [comment]
Awesome, thanks! :-) I'll merge and bump the version.

**Comment by limenet** [comment]
@valorin thank you for the quick update (and @lsfiege thanks for the PR)!

Unfortunately, the new version isn't yet on [Packagist](https://packagist.org/packages/valorin/pwned-validator). Could you please make sure the new version is available on Packagist (for Composer)?
[This guide by packagist.org](https://packagist.org/about#how-to-update-packages) might be helpful (both for manual sync and to set up automatic sync).

Thank you very much!

**Comment by valorin** [comment]
Oh, oops! Thanks for letting me know @limenet! 
Packagist was down when I tagged the update so I couldn't check it had updated and I just checked now and the package wasn't configured correctly either. It should be all updated and configured now. :-)

**Comment by limenet** [comment]
@valorin thank you very much for the quick resolution (and the package, I really like it)!

**Comment by valorin** [comment]
No worries, I'm glad you like it :-)
